version: "3"

services:
  database:
    image: mysql:5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: rc24
      MYSQL_PASSWORD: changeme
    ports:
      # Container 80 -> Host 8080
      - "3306:3306"
    volumes:
      - mail_data:/var/lib/mysql
      - ./schema/:/docker-entrypoint-initdb.d/:ro
  mail:
    build: ..
    volumes:
      - ./config:/go/src/github.com/Disconnect24/Mail-Go/config
    ports:
      # Container 80 -> Host 8080
      - "8080:80"
    # We must wait for the DB to import/etc before starting ourselves.
    depends_on:
      - "database"
    restart: on-failure
volumes:
  mail_data:
